// 共阴极
unsigned int common_anode_led[] = { 0x3f,   // 0
                                    0x06,   // 1
                                    0x5b,   // 2 
                                    0x4f,   // 3 
                                    0x66,   // 4 
                                    0x6d,   // 5 
                                    0x7d,   // 6 
                                    0x07,   // 7 
                                    0x7f,   // 8 
                                    0x6f,   // 9 
                                    0x77,   // a 
                                    0x7c,   // b 
                                    0x39,   // c 
                                    0x5e,   // d 
                                    0x79,   // e 
                                    0x71,   // f
                                    0x00    // 
                                    };
// 共阳级
unsigned int common_cathode_led[] = {   0xc0,   // 0
                                        0xf9,   // 1
                                        0xa4,   // 2
                                        0xb0,   // 3 
                                        0x99,   // 4 
                                        0x92,   // 5 
                                        0x82,   // 6 
                                        0xf8,   // 7 
                                        0x80,   // 8 
                                        0x90,   // 9 
                                        0x88,   // a 
                                        0x83,   // b 
                                        0xc6,   // c 
                                        0xa1,   // d 
                                        0x86,   // e 
                                        0x8e,   // f
                                        0xff
                                        };
